#!/bin/sh

JAVA_HOME=$HOME/soft/jdk1.8.0_31

PATH=$HOME/soft/jdk1.8.0_31/bin/:$PATH

HEAP=10G

CP='lib/JTransforms-3.1-with-dependencies.jar:lib/commons-compress-1.10.jar:lib/ejml-0.23.jar:lib/stanford-corenlp-3.5.2.jar:lib/stanford-corenlp-3.5.2-models.jar:lib/lingpipe-4.1.0.jar:bin'

java -server $PROPS  -Xmx$HEAP -XX:+UnlockCommercialFeatures -XX:+FlightRecorder -cp $CP net.crsr.ashurbanipal.PlotTodoList "$@"
